services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace/build
    command: ./tests/run_tests
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace/build
    command: ./main_app