services:
  tests:
    build:
      context: ./url_server
      dockerfile: Dockerfile
    working_dir: /workspace/build
    command: ./tests/run_tests
  
  url_server:
    build:
      context: ./url_server
      dockerfile: Dockerfile
    working_dir: /workspace/build
    command: ./main_app
    ports:
      - "12345:12345"
  
  url_client:
    build:
      context: ./url_server/src/client
      dockerfile: Dockerfile
    depends_on:
      - url_server
    command: ["python3", "main.py", "app", "12345"]
    stdin_open: true
    tty: true