services:
  url_tests:
    build:
      context: ./url_server
      dockerfile: Dockerfile
    working_dir: /workspace/build
    command: ./tests/run_tests
  
  url_server:
    build:
      context: ./url_server
      dockerfile: Dockerfile
    working_dir: /workspace/build
    command: ./main_app
    ports:
      - "12345:12345"
    volumes:
      - ./url_server/data:/workspace/build/../data
  
  url_client:
    build:
      context: ./url_server/src/client
      dockerfile: Dockerfile
    depends_on:
      - url_server
    command: ["python3", "main.py", "url_server", "12345"]
    stdin_open: true
    tty: true

  web_server:
    build:
      context: ./web_server
      dockerfile: Dockerfile
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - url_server